admin/src/web/routes/home_routes.py
"""Routes for the home pages."""
from flask import Blueprint
from src.core.controllers import home_controller
from src.core.common.decorators import LoginWrap, MaintenanceWrap

home_bp = Blueprint('home', __name__)


@home_bp.route("/")
@MaintenanceWrap.wrap
def home():
    """Route for the home page."""
    return home_controller.home()


@home_bp.route("/-")
@home_bp.route("/<int:institution_id>/")
@LoginWrap.wrap
def home_user():
    """Route for the home page for the logged-in user."""
    return home_controller.home_user()

admin/src/web/routes/register_routes.py
"""Routes for the registration pages."""
from flask import Blueprint, request
from src.core.controllers import register_controller
from src.core.common.decorators import MaintenanceWrap


register_bp = Blueprint("register", __name__, url_prefix="/register")


@register_bp.route("/", methods=["GET"])
@MaintenanceWrap.wrap
def first_registration():
    """Route for the first registration."""
    return register_controller.first_registration()


@register_bp.route("/first_form", methods=["POST"])
@MaintenanceWrap.wrap
def first_form():
    """Route for the first registration form."""
    return register_controller.first_form(request)


@register_bp.route('/confirmation/<string:hashed_email>', methods=['GET'])
@MaintenanceWrap.wrap
def confirmation(hashed_email):
    """Route for the confirmation page."""
    return register_controller.confirmation(hashed_email)


@register_bp.route("/second_form/<string:hashed_email>", methods=["POST"])
@MaintenanceWrap.wrap
def second_form(hashed_email):
    """Route for the second registration form."""
    return register_controller.second_form(request, hashed_email)


@register_bp.route("/confirm_password/<string:hashed_email>", methods=["POST"])
@MaintenanceWrap.wrap
def confirm_password(hashed_email):
    """Route for the password confirmation."""
    return register_controller.confirm_password(request, hashed_email)


@register_bp.route("/google-register", methods=["GET"])
@MaintenanceWrap.wrap
def google_register():
    """Route for google register."""
    return register_controller.google_register()


@register_bp.route("/signup-google", methods=["GET"])
@MaintenanceWrap.wrap
def google_callback():
    """Route for google register callback."""
    return register_controller.google_callback()


@register_bp.route("/second_form/google/<string:hashed_email>",
                   methods=["POST"])
@MaintenanceWrap.wrap
def google_second_form(hashed_email):
    """Route for google register form."""
    return register_controller.google_second_form(hashed_email)

admin/src/web/routes/service_requests_routes.py
"""Routes for the service request page."""
from src.core.common.decorators import LoginWrap, MaintenanceWrap
from src.core.common.decorators import PermissionWrap
from flask import Blueprint
from src.core.controllers import service_request_controller

service_requests_bp = Blueprint('service_requests', __name__,
                                url_prefix="/service-requests")


@service_requests_bp.route("/", methods=["GET"])
@MaintenanceWrap.wrap
@PermissionWrap.wrap_args(permissions=["request_index"])
@LoginWrap.wrap
def service_requests():
    """Route for the service request page."""
    return service_request_controller.service_requests()


@service_requests_bp.route("/edit/<int:service_request_id>", methods=["POST"])
@MaintenanceWrap.wrap
@PermissionWrap.wrap_args(permissions=["request_update"])
@LoginWrap.wrap
def edit_service_request(service_request_id):
    """Route for the service request edit page."""
    return service_request_controller.edit_service_request(
        service_request_id
    )


@service_requests_bp.route("/delete", methods=["POST"])
@MaintenanceWrap.wrap
@PermissionWrap.wrap_args(permissions=["request_destroy"])
@LoginWrap.wrap
def delete_service_request():
    """Route for the service request delete page."""
    return service_request_controller.delete_service_request()


@service_requests_bp.route("/service-request/<int:service_request_id>/notes",
                           methods=["GET"]
                           )
@MaintenanceWrap.wrap
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["request_update"])
def notes(service_request_id):
    """Route for the service request notes page."""
    return service_request_controller.notes(service_request_id)


@service_requests_bp.route(
        "/service-request/<int:service_request_id>/new_note",
        methods=["POST"]
    )
@MaintenanceWrap.wrap
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["request_update"])
def new_note(service_request_id):
    """Route for the service request new note page."""
    return service_request_controller.new_note(service_request_id)

admin/src/web/routes/superuser_routes.py
"""Routes for the superuser pages."""
from flask import Blueprint, request
from src.core.controllers import users_config_controller
from src.core.controllers import institutions_config_controller
from src.core.controllers import site_config_controller as config
from src.core.common.decorators import PermissionWrap
from src.core.common.decorators import LoginWrap


super_bp = Blueprint('super', __name__, url_prefix='/admin')


# SITE CONFIG
@super_bp.route("/site-config", methods=["GET"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["config_show"])
def view_config():
    """Route for the site config page."""
    return config.view_config()


@super_bp.route('/edit-config', methods=['GET', 'POST'])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["config_update"])
def edit_config():
    """Route for the site config edit page."""
    return config.edit_config(request)


# USERS
@super_bp.route("/users", methods=["GET"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_index"])
def users():
    """Route for the users page."""
    return users_config_controller.users()


@super_bp.route("/users/active", methods=["GET"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_index"])
def active():
    """Route for the active users page."""
    return users_config_controller.active()


@super_bp.route("/users/inactive", methods=["GET"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_index"])
def inactive():
    """Route for the inactive users page."""
    return users_config_controller.inactive()


@super_bp.route("/users/search", methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_index"])
def search():
    """Route for the users search page."""
    return users_config_controller.search()


@super_bp.route("/users/delete-user", methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_destroy"])
def delete_user():
    """Route for the user delete page."""
    return users_config_controller.delete_user()


@super_bp.route("/users/add-user", methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_create"])
def add_user():
    """Route for the user add page."""
    return users_config_controller.add_user()


@super_bp.route('/confirmation/<string:hashed_email>', methods=['GET'])
def user_added_confirmation(hashed_email):
    """Route for the confirmation page."""
    return users_config_controller.user_added_confirmation(hashed_email)


@super_bp.route("/users/edit-user/<int:user_id>", methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_update"])
def edit_user(user_id):
    """Route for the user edit page."""
    return users_config_controller.edit_user(user_id)


@super_bp.route("/users/user-roles/<int:user_id>", methods=["GET"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_update"])
def roles(user_id):
    """Route for the user roles page."""
    return users_config_controller.roles(user_id)


@super_bp.route("/users/user-roles/<int:user_id>/add-role", methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_update"])
def add_role(user_id):
    """Route for the user roles add page."""
    return users_config_controller.add_role(user_id)


@super_bp.route("/users/user-roles/<int:user_id>/delete-role",
                methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_update"])
def delete_role(user_id):
    """Route for the user roles delete page."""
    return users_config_controller.delete_role(user_id)


# INSTITUTIONS
@super_bp.route("/institutions", methods=["GET"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["institution_index",
                                       "institution_show"])
def institutions():
    """Route for the institutions page."""
    return institutions_config_controller.institutions()


@super_bp.route("/institutions/add-institution", methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["institution_create",
                                       "institution_activate",
                                       "institution_deactivate"])
def add_institution():
    """Route for the institution add page."""
    return institutions_config_controller.add_institution()


@super_bp.route("/institutions/edit-institution/<int:institution_id>",
                methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["institution_update",
                                       "institution_activate",
                                       "institution_deactivate"])
def edit_institution(institution_id):
    """Route for the institution edit page."""
    return institutions_config_controller.edit_institution(institution_id)


@super_bp.route("/institutions/delete-institution",
                methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["institution_destroy"])
def delete_institution():
    """Route for the institution delete page."""
    return institutions_config_controller.delete_institution()

admin/src/web/templates/pages/configuration.html
{% extends "layout.html" %}
{% block title %} Configuración del Sitio{% endblock %}
{% block head %}{{ super() }}{% endblock %}
{% block content %}
<div class="container mt-4">
    <h2 class="mb-4 text-center" style="align-self: center">Configuraci&oacute;n del Sistema</h2>
    <ul class="list-group">
        <li class="list-group-item">
            <strong>Elementos por P&aacute;gina:</strong>
            <p class="mt-2">
                <span class="badge badge-primary badge-pill">
                    {{ items_per_page }}
                </span>
            </p>
        </li>
        <li class="list-group-item">
            <strong>Modo Mantenimiento:</strong>
            <p class="mt-2">
                <span class="badge badge-{{ 'success' if maintenance_mode else 'danger' }} badge-pill">
                    {{ 'Habilitado' if maintenance_mode else 'Deshabilitado' }}
                </span>
            </p>
        </li>
        <li class="list-group-item">
            <strong>Mensaje de Mantenimiento del Sitio:</strong>
            <p class="mt-2">{% if maintenance_message %}{{ maintenance_message }}
                            {% else %}No tiene un mensaje de mantenimiento cargado
                            {% endif %}</p>
        </li>
        <li class="list-group-item">
            <strong>Informaci&oacute;n de Contacto:</strong>
            <p class="mt-2">{% if contact_info %}{{ contact_info }}
                            {% else %}No tiene informaci&oacute;n de contacto cargada
                            {% endif %}
            </p>
        </li>
    </ul>
    <a href="{{ url_for('super.edit_config') }}" class="card-link">
        <button type="button" class="btn btn-info mt-3">
            Editar
        </button>
    </a>
</div>
{% endblock %}

admin/src/web/templates/pages/error.html
<!DOCTYPE html>
<html lang="es">
	<head>
		{% block head %}
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="{{ url_for('static', filename = 'css/style.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='css/error.css') }}" />
		<link
			rel="stylesheet"
			href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
			integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
			crossorigin="anonymous"
		/>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" />
		<title>{% block title %} Error {% endblock %}</title>
		{% endblock %}
	</head>
	<body>
		<div id="main">
			{% block content %}
			<div class="d-flex justify-content-center align-items-center" style="height: 80vh">
				<div class="card bg-dark text-center text-white col-8" style="min-height: 40vh">
					<div class="card-body d-flex flex-column justify-content-center align-items-center">
						<h1 class="card-title">:(</h1>
						<h3 class="card-title">{{ error_name }}</h3>
						<h6 class="card-subtitle mb-2 pb-4">{{ error_description }}</h6>

						{% if is_authenticated(session) %}
							<a href="{{ url_for('home.home_user') }}" class="card-link">
						{% else %}
							<a href="{{ url_for('home.home') }}" class="card-link">
						{% endif %}
							<button class="btn btn-primary">Volver al inicio</button> 
						</a>
					</div>
				</div>
			</div>

			{% endblock %}
		</div>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script
			src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
			integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
			crossorigin="anonymous"
		></script>
		<script
			src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
			integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
			crossorigin="anonymous"
		></script>
	</body>
</html>

admin/src/web/templates/pages/home.html
{% extends "layout.html" %}
{% block title %}CIDEPINT: Administración{% endblock %}
{% block head %}{{ super() }}
<script src="{{ url_for('static', filename='js/navbar.js') }}"></script>
{% endblock %}
{% block content %}
{% if not is_authenticated(session) %}
{% include 'components/cards/welcome_card.html' %}
{% else %}
{% include 'components/cards/logged_card.html' %}
{% endif %}
{% endblock %}

admin/src/web/templates/pages/institution_roles.html
{% extends "layout.html" %}
{% block title %} Usuarios de institución {% endblock %}
{% block head %}{{ super() }}
<script src="{{ url_for('static', filename='js/openModal.js') }}"></script>
<script src="{{ url_for('static', filename='js/userModals.js') }}"></script>
{% endblock %}
{% block content %}
{% include "modules/institution_roles/roles_list.html" %}
{% include "components/pagination.html" %}
{% endblock %}

admin/src/web/templates/pages/institutions.html
{% extends "layout.html" %}
{% block title %} Instituciones {% endblock %}
{% block head %}{{ super() }}
<script src="{{ url_for('static', filename='js/openModal.js') }}"></script>
<script src="{{ url_for('static', filename='js/formValidations.js') }}"></script>
<script src="{{ url_for('static', filename='js/institutionModals.js') }}">
</script>
<script src="{{ url_for('static', filename='js/leafletMap.js') }}">
</script>
{% endblock %}
{% block content %}
{% include "modules/institutions/institutions_list.html" %}
{% include "modules/institutions/modals/institution_add.html" %}
{% include "modules/institutions/modals/institution_delete.html" %}
{% include "modules/institutions/modals/institution_edit.html" %}
{% include "modules/institutions/modals/institution_view.html" %}
{% include "components/pagination.html" %}
{% endblock %}

admin/src/web/templates/pages/notes.html
{% extends "layout.html" %}
{% block title %} Notas {% endblock %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h5>{{ service_request.title }}</h5>
            <h6 class="text-muted"> Notas</h6>
        </div>
        <div class="card-body">
            <div class="list-group">
                {% if not elements %}
                <h5 class="text-center pb-4 pt-4"> No hay notas en esta Solicitud </h5>
                {% endif %}
                {% for element in elements|sort(attribute='inserted_at')%}
                <div
                     class="list-group-item list-group-item-action {% if element.user.email == user_email %} bg-white {% else %} bg-light {% endif %} ">
                    <div class="d-flex w-100 justify-content-between flex-column flex-sm-row">
                        <h6 class="pt-2"> {{ element.text }} </h6>
                        <h6 class="pt-2"> {{ element.user.email }} </h6>
                    </div>
                </div>
                <form> </form>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="py-4 row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Agregar Nota</div>
                <div class="card-body">
                    <form id="chat-form" method="POST"
                          action="{{ url_for('service_requests.new_note', service_request_id=service_request.id) }}">
                        <div class="input-group mb-3">
                            <input type="text" id="message" name="message" class="form-control"
                                   placeholder="Escribe tu mensaje..." required />
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary">Subir</button>
                                </div>
                                </div>
                                </form>
                                </div>
                                </div>
                                </div>
                                </div>
                                </div>

{% endblock %}

admin/src/web/templates/pages/pswrd_change.html
{% extends "layout.html" %} {% block title %} CIDEPINT: Cambiar Contraseña{% endblock %} {%
block head %} {{ super() }}
<script src="{{ url_for('static', filename='js/formValidations.js') }}"></script>
<script src="{{ url_for('static', filename='js/changePassword.js') }}"></script>
{% endblock %} {% block content %}
<div class="card">
    <div class="card-body text-center row">
        <div class="d-md-inline d-none col-3"></div>
        <div class="col">
            <h4 class="card-title">Cambiar Contraseña</h4>
            <div class="dropdown-divider pb-4"></div>
            <form method="POST"
                  action="{{ url_for('register.confirm_password', hashed_email=hashed_email) }}" onsubmit="return validateChangePassword()">

                <div class="form-group">
                    <label for="inputNewPassword"> Contraseña*</label>
                    <input type="password" class="form-control" id="inputNewPassword"
                           name="inputNewPassword"
                           onblur="validatePassword('inputNewPassword', 'newPasswordError'); validateChangePassword()"
                           aria-describedby="newPasswordError"
                           required>
                    <small id="newPasswordError" class="form-text text-danger"></small>
                </div>

                <div class="form-group">
                    <label for="inputConfirmPassword"> Confirmar Contraseña*</label>
                    <input type="password" class="form-control" id="inputConfirmPassword"
                           name="inputConfirmPassword"
                           onblur="validateChangePassword()"
                           aria-describedby="confirmPasswordError"
                           required>
                    <small id="confirmPasswordError" class="form-text text-danger"></small>
                </div>

                <button type="submit" class="btn btn-primary">Confirmar</button>

                <a type="button" class="btn btn-primary text-white" href="{{ url_for('home.home') }}">Cancelar</a>
            </form>
        </div>
        <div class="d-md-inline d-none col-3"></div>
    </div>
</div>
{% endblock %}

admin/src/web/templates/pages/roles.html
{% extends "layout.html" %}
{% block title %} Usuarios: Roles {% endblock %}
{% block head %}{{ super() }}
<script src="{{ url_for('static', filename='js/formValidations.js') }}"></script>
<script src="{{ url_for('static', filename='js/openModal.js') }}"></script>
<script src="{{ url_for('static', filename='js/roles.js') }}"></script>
{% endblock %}
{% block content %}
<div class="container">
    <h3 class="text-center pb-4 pt-2"> {{ title }} </h3>
    <form method="POST" action="{{ url_for('super.add_role',user_id=user_id) }}"
          class="mx-1 row justify-content-start align-items-center flex-column flex-sm-row pb-4">

        <div class="form-group pr-4">
            <label for="inputInstitution"> Institución </label>
            <select class="form-control" id="inputInstitution" name="inputInstitution">
                <option value="" disabled selected>Seleccionar una Institución</option>
                {% for institution in institutions %}
                <option value="{{ institution.id }}">{{ institution.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group pr-4">
            <label for="inputRole"> Rol </label>
            <select class="form-control" id="inputRole" name="inputRole">
                <option value="" disabled selected>Seleccionar un Rol</option>
                {% for role in roles %}
                <option value="{{ role.id }}">{{ role.name }}</option>
                {% endfor %}
            </select>
        </div>

        <button id="addRoleButton" type="submit" class="btn btn-primary mt-3">Agregar</button>
    </form>

    <div class="list-group ">
        {% for element in elements %}
        <div class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between flex-column flex-sm-row">
                <h6 class="pt-2"> {{ element.institution }} </h6>
                <h6 class="pt-2"> {{ element.role }} </h6>
                <div>

                    <button type="button" onclick="deleteRole(this)" data-element="{{ element }}"
                            class="btn btn-outline-danger">Eliminar</button>

                </div>
            </div>

        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% include "modules/users/modals/role_delete.html" %}

admin/src/web/templates/pages/service_requests.html
{% extends "layout.html" %}
{% block title %} Solicitudes de Servicio {% endblock %}
{% block head %}{{ super() }}
<script src="{{ url_for('static', filename='js/openModal.js') }}"></script>
<script src="{{ url_for('static', filename='js/serviceRequestModals.js') }}"></script>
<script src="{{ url_for('static', filename='js/formValidations.js') }}"></script>
{% endblock %}
{% block content %}
{% include "modules/service_requests/service_requests_list.html" %}
{% include "modules/service_requests/modals/service_request_view.html" %}
{% include "modules/service_requests/modals/service_request_edit.html" %}
{% include "modules/service_requests/modals/service_request_delete.html" %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {% for page_num in elements.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if page_num == elements.page %}
                        <a class="btn btn-info mb-4" href="{{ url_for(request.endpoint, page=page_num, service_id=service_id) }}">{{ page_num }}</a>
                    {% else %}
                        <a class="btn btn-outline-info mb-4" href="{{ url_for(request.endpoint, page=page_num, service_id=service_id) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

admin/src/web/templates/pages/services.html
{% extends "layout.html" %}
{% block title %} Servicios {% endblock %}
{% block head %}{{ super() }}
<script src="{{ url_for('static', filename='js/openModal.js') }}"></script>
<script src="{{ url_for('static', filename='js/serviceModals.js') }}"></script>
<script src="{{ url_for('static', filename='js/formValidations.js') }}"></script>
{% endblock %}
{% block content %}
{% include "modules/services/services_list.html" %}
{% include "modules/services/modals/service_view.html" %}
{% include "modules/services/modals/service_add.html" %}
{% include "modules/services/modals/service_edit.html" %}
{% include "modules/services/modals/service_delete.html" %}
{% include "components/pagination.html" %}
{% endblock %}

admin/src/web/templates/pages/users.html
{% extends "layout.html" %}
{% block title %} Usuarios{% endblock %}
{% block head %}{{ super() }}
<script src="{{ url_for('static', filename='js/formValidations.js') }}"></script>
<script src="{{ url_for('static', filename='js/openModal.js') }}"></script>
<script src="{{ url_for('static', filename='js/userModals.js') }}"></script>
{% endblock %}
{% block content %}
{% include "modules/users/modals/user_view.html" %}
{% include "modules/users/modals/user_edit.html" %}
{% include "modules/users/modals/user_delete.html" %}
{% include "modules/users/modals/user_add.html" %}
{% include "modules/users/modals/user_roles.html" %}
{% include "modules/users/users_list.html" %}
{% include "components/pagination.html" %}
{% endblock %}