admin/src/web/routes/superuser_routes.py
"""Routes for the superuser pages."""
from flask import Blueprint, request
from src.core.controllers import users_config_controller
from src.core.controllers import institutions_config_controller
from src.core.controllers import site_config_controller as config
from src.core.common.decorators import PermissionWrap
from src.core.common.decorators import LoginWrap


super_bp = Blueprint('super', __name__, url_prefix='/admin')


# SITE CONFIG
@super_bp.route("/site-config", methods=["GET"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["config_show"])
def view_config():
    """Route for the site config page."""
    return config.view_config()


@super_bp.route('/edit-config', methods=['GET', 'POST'])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["config_update"])
def edit_config():
    """Route for the site config edit page."""
    return config.edit_config(request)


# USERS
@super_bp.route("/users", methods=["GET"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_index"])
def users():
    """Route for the users page."""
    return users_config_controller.users()


@super_bp.route("/users/active", methods=["GET"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_index"])
def active():
    """Route for the active users page."""
    return users_config_controller.active()


@super_bp.route("/users/inactive", methods=["GET"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_index"])
def inactive():
    """Route for the inactive users page."""
    return users_config_controller.inactive()


@super_bp.route("/users/search", methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_index"])
def search():
    """Route for the users search page."""
    return users_config_controller.search()


@super_bp.route("/users/delete-user", methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_destroy"])
def delete_user():
    """Route for the user delete page."""
    return users_config_controller.delete_user()


@super_bp.route("/users/add-user", methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_create"])
def add_user():
    """Route for the user add page."""
    return users_config_controller.add_user()


@super_bp.route('/confirmation/<string:hashed_email>', methods=['GET'])
def user_added_confirmation(hashed_email):
    """Route for the confirmation page."""
    return users_config_controller.user_added_confirmation(hashed_email)


@super_bp.route("/users/edit-user/<int:user_id>", methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_update"])
def edit_user(user_id):
    """Route for the user edit page."""
    return users_config_controller.edit_user(user_id)


@super_bp.route("/users/user-roles/<int:user_id>", methods=["GET"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_update"])
def roles(user_id):
    """Route for the user roles page."""
    return users_config_controller.roles(user_id)


@super_bp.route("/users/user-roles/<int:user_id>/add-role", methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_update"])
def add_role(user_id):
    """Route for the user roles add page."""
    return users_config_controller.add_role(user_id)


@super_bp.route("/users/user-roles/<int:user_id>/delete-role",
                methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["user_update"])
def delete_role(user_id):
    """Route for the user roles delete page."""
    return users_config_controller.delete_role(user_id)


# INSTITUTIONS
@super_bp.route("/institutions", methods=["GET"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["institution_index",
                                       "institution_show"])
def institutions():
    """Route for the institutions page."""
    return institutions_config_controller.institutions()


@super_bp.route("/institutions/add-institution", methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["institution_create",
                                       "institution_activate",
                                       "institution_deactivate"])
def add_institution():
    """Route for the institution add page."""
    return institutions_config_controller.add_institution()


@super_bp.route("/institutions/edit-institution/<int:institution_id>",
                methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["institution_update",
                                       "institution_activate",
                                       "institution_deactivate"])
def edit_institution(institution_id):
    """Route for the institution edit page."""
    return institutions_config_controller.edit_institution(institution_id)


@super_bp.route("/institutions/delete-institution",
                methods=["POST"])
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["institution_destroy"])
def delete_institution():
    """Route for the institution delete page."""
    return institutions_config_controller.delete_institution()

admin/src/web/templates/modules/users/modals/role_delete.html
{% extends "/components/modals/modal_template.html" %}
{% block modal_id %}role_delete{% endblock %}
{% block header %} Eliminar Rol {% endblock %}
{% block cuerpo %}
<div id="confirm-message" class="modal-body">
    ¿Estás seguro de que deseas eliminar este rol? Esta acción no puede deshacerse.
</div>
{% endblock %}
{% block footer %}

<form id="delete-form" method="POST" action="{{ url_for('super.delete_role', user_id=user_id) }}">
    <input id="role_id" type="hidden" name="role_id" value="">
    <input id="institution_id" type="hidden" name="institution_id" value="">
    <button id="confirm-action" type="submit" class="btn btn-primary confirm-button"> Confirmar
    </button>

    <button id="dismiss-action" type="button" class="btn btn-secondary close-button"
            data-dismiss="modal"> Cerrar </button>
</form>
{% endblock %}

admin/src/web/templates/modules/users/modals/user_add.html
{% extends "/components/modals/modal_template.html" %}
{% block modal_id %}user_add{% endblock %}
<!-- Acá iría el nombre del usuario -->
{% block header %} Agregar usuario {% endblock %}
{% block cuerpo %}
<!-- Acá iría todo el HTML correspondiente a la edición del usuario -->
<div id="confirm-message" class="modal-body modal-scrollable">
    <div class="col">
        <form id="add-form" method="POST" action="{{ url_for('super.add_user') }}">
            <div class="form-group">
                <label for="inputEmail"> Dirección de email *</label>
                <input required type="email" class="form-control" id="inputEmailUsr"
                       name="inputEmail" placeholder="nombre@ejemplo.com"
                       onblur="validateEmail('inputEmailUsr', 'emailErrorUsr'); allFieldsValid()"
                       aria-describedby="emailErrorUsr" />
                <small id="emailErrorUsr" class="form-text text-danger"></small>
            </div>
            <div class="form-group">
                <label for="inputName"> Nombre * </label>
                <input required type="text" class="form-control" id="inputNameUsr" name="inputName"
                       placeholder="John" onblur="validateJustText('inputNameUsr', 'nameErrorUsr'); allFieldsValid();"
                       aria-describedby="nameErrorUsr" />
                <small id="nameErrorUsr" class="form-text text-danger"></small>
            </div>
            <div class="form-group">
                <label for="inputSurname"> Apellido * </label>
                <input required type="text" class="form-control" id="inputSurnameUsr"
                       name="inputSurname" placeholder="Doe"
                       onblur="validateJustText('inputSurnameUsr', 'surnameErrorUsr'); allFieldsValid()"
                       aria-describedby="surnameErrorUsr" />
                <small id="surnameErrorUsr" class="form-text text-danger"></small>
            </div>
            <div class="form-group">
                <label for="inputUsername"> Nombre de usuario * </label>
                <input required type="text" class="form-control" id="inputUsernameUsr"
                       name="inputUsername" placeholder="johndoe"
                       onblur="validateUsername('inputUsernameUsr', 'usernameErrorUsr'); allFieldsValid()"
                       aria-describedby="usernameErrorUsr" />
                <small id="usernameErrorUsr" class="form-text text-danger"></small>
            </div>

            <div class="form-group">
                <label for="inputPassword"> Contraseña *</label>
                <input required type="password" class="form-control" id="inputPasswordUsr"
                       name="inputPassword"
                       onblur="validatePassword('inputPasswordUsr', 'passwordErrorUsr'); allFieldsValid()"
                       aria-describedby="passwordErrorUsr" />
                <small id="passwordErrorUsr" class="form-text text-danger"></small>
            </div>

            <div class="form-group">
                <label for="inputDocumentType">Tipo de Documento *</label>
                <select onblur="allFieldsValid()" required class="form-control" id="inputDocumentType" name="inputDocumentType">
                    <option value="" disabled selected>Seleccionar un tipo de Documento</option>
                    <option value="DNI">DNI</option>
                    <option value="Pasaporte">Pasaporte</option>
                </select>
            </div>

            <div class="form-group">
                <label for="inputDocument">Número de Documento *</label>
                <input required type="text" class="form-control" id="inputDocumentUsr" name="inputDocument"
                       placeholder="12345678"
                       onblur="validateJustNumber('inputDocumentUsr', 'documentErrorUsr'); allFieldsValid()"
                       aria-describedby="documentErrorUsr">
                <small id="documentErrorUsr" class="form-text text-danger"></small>
            </div>

            <div class="form-group">
                <label for="inputGender">Género *</label>
                <select onblur="allFieldsValid()" required class="form-control" id="inputGender" name="inputGender">
                    <option value="" disabled selected>Seleccionar un Género</option>
                    <option value="Masculino">Masculino</option>
                    <option value="Femenino">Femenino</option>
                    <option value="No binario">No binario</option>
                </select>
            </div>
            <div class="form-group">
                <label for="inputAddress">Dirección *</label>
                <input required type="text" class="form-control" id="inputAddressUsr" name="inputAddress"
                       onblur="validateDireccion('inputAddressUsr', 'addressErrorUsr'); allFieldsValid()"
                       aria-describedby="addressErrorUsr">
                <small id="addressErrorUsr" class="form-text text-danger"></small>
            </div>

            <div class="form-group">
                <label for="inputPhoneNumber">Número de teléfono *</label>
                <input required type="text" class="form-control" id="inputPhoneNumberUsr"
                       name="inputPhoneNumber"
                       onblur="validatePhoneNumber('inputPhoneNumberUsr', 'phoneNumberErrorUsr'); allFieldsValid();"
                       aria-describedby="phoneNumberErrorUsr">
                <small id="phoneNumberErrorUsr" class="form-text text-danger"></small>
            </div>

            <button type="submit" disabled class="btn btn-primary"> Registrar Usuario
            </button>

            <button type="button" class="btn btn-secondary close-button" data-dismiss="modal">
                Cerrar </button>
        </form>
    </div>
</div>
{% endblock %}
{% block footer %}

{% endblock %}

admin/src/web/templates/modules/users/modals/user_delete.html
{% extends "/components/modals/modal_template.html" %}
{% block modal_id %}user_delete{% endblock %}
{% block header %} Eliminar Usuario {% endblock %}
{% block cuerpo %}
<div id="confirm-message" class="modal-body">
    ¿Estás seguro de que deseas eliminar este usuario? Esta acción no puede deshacerse.
</div>
{% endblock %}
{% block footer %}

<form id="delete-form" method="POST" action="{{ url_for('super.delete_user') }}">
    <input id="user-id" type="hidden" name="user_id" value="">
    <button id="confirm-action" type="submit" class="btn btn-primary confirm-button"> Confirmar
    </button>

    <button id="dismiss-action" type="button" class="btn btn-secondary close-button"
            data-dismiss="modal"> Cerrar </button>
</form>
{% endblock %}

admin/src/web/templates/modules/users/modals/user_edit.html
{% extends "/components/modals/modal_template.html" %}
{% block modal_id %}user_edit{% endblock %}
<!-- Acá iría el nombre del usuario -->
{% block header %} Editar usuario {% endblock %}
{% block cuerpo %}
<!-- Acá iría todo el HTML correspondiente a la edición del usuario -->
<div id="confirm-message" class="modal-body modal-scrollable">
    <div class="col">
        <form id="edit-form" method="POST" action="">
            <div class="form-group form-check">
                <input class="form-check-input" type="checkbox" value="1" id="inputActive" name="inputActive">
                <label class="form-check-label" for="inputActive">
                    ¿Usuario Activo?
                </label>
            </div>

            <div class="form-group">
                <label for="inputEmail"> Dirección de email *</label>
                <input required type="email" class="form-control" id="inputEmail" name="inputEmail"
                       placeholder="nombre@ejemplo.com"
                       onblur="validateEmail('inputEmail', 'emailError'); allFieldsValid()"
                       aria-describedby="emailError" />
                <small id="emailError" class="form-text text-danger"></small>
            </div>
            <div class="form-group">
                <label for="inputName"> Nombre *</label>
                <input required type="text" class="form-control" id="inputName" name="inputName"
                       placeholder="John" onblur="validateJustText('inputName', 'nameError'); allFieldsValid()"
                       aria-describedby="nameError" />
                <small id="nameError" class="form-text text-danger"></small>
            </div>
            <div class="form-group">
                <label for="inputSurname"> Apellido *</label>
                <input required type="text" class="form-control" id="inputSurname"
                       name="inputSurname" placeholder="Doe"
                       onblur="validateJustText('inputSurname', 'surnameError'); allFieldsValid()"
                       aria-describedby="surnameError" />
                <small id="surnameError" class="form-text text-danger"></small>
            </div>
            <div class="form-group">
                <label for="inputUsername"> Nombre de usuario *</label>
                <input required type="text" class="form-control" id="inputUsername"
                       name="inputUsername" placeholder="johndoe"
                       onblur="validateUsername('inputUsername', 'usernameError'); allFieldsValid()"
                       aria-describedby="usernameError" />
                <small id="usernameError" class="form-text text-danger"></small>
            </div>

            <div class="form-group">
                <label for="inputDocumentType">Tipo de Documento *</label>
                <select onblur="allFieldsValid()" required class="form-control" id="inputDocumentType" name="inputDocumentType">
                    <option value="" disabled selected>Seleccionar un tipo de Documento</option>
                    <option value="DNI">DNI</option>
                    <option value="Pasaporte">Pasaporte</option>
                </select>
            </div>

            <div class="form-group">
                <label for="inputDocument">Número de Documento *</label>
                <input required type="text" class="form-control" id="inputDocument" name="inputDocument"
                       placeholder="12345678"
                       onblur="validateJustNumber('inputDocument', 'documentError'); allFieldsValid()"
                       aria-describedby="documentError">
                <small id="documentError" class="form-text text-danger"></small>
            </div>

            <div class="form-group">
                <label for="inputGender">Género *</label>
                <select onblur="allFieldsValid()" class="form-control" id="inputGender" name="inputGender">
                    <option value="" disabled selected>Seleccionar un Género</option>
                    <option value="Masculino">Masculino</option>
                    <option value="Femenino">Femenino</option>
                    <option value="No binario">No binario</option>
                </select>
            </div>
            <div class="form-group">
                <label for="inputAddress">Dirección *</label>
                <input required type="text" class="form-control" id="inputAddress" name="inputAddress"
                       onblur="validateDireccion('inputAddress', 'addressError'); allFieldsValid()"
                       aria-describedby="addressError">
                <small id="addressError" class="form-text text-danger"></small>
            </div>

            <div class="form-group">
                <label for="inputPhoneNumber">Número de teléfono *</label>
                <input required type="text" class="form-control" id="inputPhoneNumber"
                       name="inputPhoneNumber"
                       onblur="validatePhoneNumber('inputPhoneNumber', 'phoneNumberError'); allFieldsValid()"
                       aria-describedby="phoneNumberError">
                <small id="phoneNumberError" class="form-text text-danger"></small>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block footer %}
<button type="submit" form="edit-form" class="btn btn-primary"> 
    Confirmar
</button>

<button type="button" class="btn btn-secondary close-button" data-dismiss="modal">
    Cerrar 
</button>
{% endblock %}

admin/src/web/templates/modules/users/modals/user_roles.html
{% extends "/components/modals/modal_template.html" %}
{% block modal_id %}user_roles{% endblock %}
<!-- Acá iría el nombre del usuario -->
{% block header %} Ver usuario {% endblock %}
{% block cuerpo %}
<!-- Acá iría todo el HTML correspondiente a la vista del usuario -->
<div id="confirm-message" class="modal-body modal-scrollable">
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <h6> Nombre </h6>
            </div>
            <div class="col-sm">
                <p id="user-first-name"> placeholder </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <h6> Apellido </h6>
            </div>
            <div class="col-sm">
                <p id="user-last-name"> placeholder </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <h6> Email </h6>
            </div>
            <div class="col-sm">
                <p id="user-email"> placeholder </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <h6> Nombre de usuario </h6>
            </div>
            <div class="col-sm">
                <p id="user-username"> placeholder </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <h6> Teléfono </h6>
            </div>
            <div class="col-sm">
                <p id="user-phone"> placeholder </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <h6> Dirección </h6>
            </div>
            <div class="col-sm">
                <p id="user-address"> placeholder </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <h6> Género </h6>
            </div>
            <div class="col-sm">
                <p id="user-gender"> placeholder </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <h6> DNI o pasaporte </h6>
            </div>
            <div class="col-sm">
                <p id="user-dni"> placeholder </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <h6> Activo </h6>
            </div>
            <div class="col-sm">
                <p id="user-active"> placeholder </p>
            </div>
        </div>
    </div>

</div>
{% endblock %}
{% block footer %}
<button type="button" class="btn btn-secondary close-button" data-dismiss="modal">
    Cerrar </button>
{% endblock %}

admin/src/web/templates/modules/users/modals/user_view.html
{% extends "/components/modals/modal_template.html" %}
{% block modal_id %}user_view{% endblock %}
<!-- Acá iría el nombre del usuario -->
{% block header %} Ver usuario {% endblock %}
{% block cuerpo %}
<!-- Acá iría todo el HTML correspondiente a la vista del usuario -->
<div id="confirm-message" class="modal-body modal-scrollable">
<div class="container">
    <div class="row">
        <div class="col-sm">
            <h6> Nombre </h6>
        </div>
        <div class="col-sm">
            <p id="user-first-name"> placeholder </p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <h6> Apellido </h6>
        </div>
        <div class="col-sm">
            <p id="user-last-name"> placeholder </p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <h6> Email </h6>
        </div>
        <div class="col-sm">
            <p id="user-email"> placeholder </p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <h6> Nombre de usuario </h6>
        </div>
        <div class="col-sm">
            <p id="user-username"> placeholder </p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <h6> Teléfono </h6>
        </div>
        <div class="col-sm">
            <p id="user-phone"> placeholder </p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <h6> Dirección </h6>
        </div>
        <div class="col-sm">
            <p id="user-address"> placeholder </p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <h6> Género </h6>
        </div>
        <div class="col-sm">
            <p id="user-gender"> placeholder </p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <h6> DNI o pasaporte </h6>
        </div>
        <div class="col-sm">
            <p id="user-dni"> placeholder </p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <h6> Estado </h6>
        </div>
        <div class="col-sm">
            <p id="user-active"> placeholder </p>
        </div>
    </div>
</div>

</div>
{% endblock %}
{% block footer %}
<button type="button" class="btn btn-outline-info edit-button" onclick="editUser(this)" id="edit-button">
    Editar
</button>
<button type="button" class="btn btn-secondary close-button" data-dismiss="modal">
    Cerrar
</button>
{% endblock %}