admin/src/web/routes/service_requests_routes.py
"""Routes for the service request page."""
from src.core.common.decorators import LoginWrap, MaintenanceWrap
from src.core.common.decorators import PermissionWrap
from flask import Blueprint
from src.core.controllers import service_request_controller

service_requests_bp = Blueprint('service_requests', __name__,
                                url_prefix="/service-requests")


@service_requests_bp.route("/", methods=["GET"])
@MaintenanceWrap.wrap
@PermissionWrap.wrap_args(permissions=["request_index"])
@LoginWrap.wrap
def service_requests():
    """Route for the service request page."""
    return service_request_controller.service_requests()


@service_requests_bp.route("/edit/<int:service_request_id>", methods=["POST"])
@MaintenanceWrap.wrap
@PermissionWrap.wrap_args(permissions=["request_update"])
@LoginWrap.wrap
def edit_service_request(service_request_id):
    """Route for the service request edit page."""
    return service_request_controller.edit_service_request(
        service_request_id
    )


@service_requests_bp.route("/delete", methods=["POST"])
@MaintenanceWrap.wrap
@PermissionWrap.wrap_args(permissions=["request_destroy"])
@LoginWrap.wrap
def delete_service_request():
    """Route for the service request delete page."""
    return service_request_controller.delete_service_request()


@service_requests_bp.route("/service-request/<int:service_request_id>/notes",
                           methods=["GET"]
                           )
@MaintenanceWrap.wrap
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["request_update"])
def notes(service_request_id):
    """Route for the service request notes page."""
    return service_request_controller.notes(service_request_id)


@service_requests_bp.route(
        "/service-request/<int:service_request_id>/new_note",
        methods=["POST"]
    )
@MaintenanceWrap.wrap
@LoginWrap.wrap
@PermissionWrap.wrap_args(permissions=["request_update"])
def new_note(service_request_id):
    """Route for the service request new note page."""
    return service_request_controller.new_note(service_request_id)

admin/src/web/templates/modules/service_requests/filters.html
<div class="mx-1 row justify-content-between align-items-center flex-column flex-sm-row ">
    <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        Filtros
    </a>
    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            <form action= "{{ url_for('service_requests.service_requests') }}" method="get" class="form-inline mb-4 align-items-center flex-column flex-sm-row">
                <select id="service-type" name="service-type" class="form-control mr-sm-3">
                    <option value="" disabled selected>Tipo de Servicio</option>
                    <option value="Análisis">Análisis</option>
                    <option value="Consultoría">Consultoría</option>
                    <option value="Desarrollo">Desarrollo</option>
                </select>
    
                <select id="request-status" name="request-status" class="form-control mr-sm-3">
                    <option value="" disabled selected>Estado de la Solicitud</option>
                    <option value="Aceptada">Aceptada</option>
                    <option value="Rechazada">Rechazada</option>
                    <option value="En proceso">En proceso</option>
                    <option value="Finalizada">Finalizada</option>
                    <option value="Cancelada">Cancelada</option>
                </select>
    
                <label for="start-date" class="mr-2">Desde:</label>
                <input id="start-date" name="start-date" class="form-control mr-2" type="date">
                <label for="end-date" class="mr-2">Hasta:</label>
                <input id="end-date" name="end-date" class="form-control mr-sm-3" type="date">
            
                <input id="request-email" name="request-email" class="form-control mr-3" type="text" placeholder="Ingrese un email">
                <button id="search-button" class="btn btn-primary my-2 my-sm-0" type="submit">Filtrar</button>
            </form>
        </div>
        </div>
</div>

admin/src/web/templates/modules/service_requests/service_requests_actions.html
<div>
        {% if permissions.show %}
        <button type="button" class="btn btn-outline-primary view-button"
                onclick= "viewServiceRequest(this)" 
                data-element="{{ parse_service_request(element) }}"
                data-url="{{ url_for('service_requests.edit_service_request', service_request_id=element['id']) }}">
                Ver
        </button>
        {% endif %}

        {% if permissions.update %}
        <a href="{{ url_for('service_requests.notes', service_request_id=element['id']) }}"
        class="btn btn-outline-secondary text-decoration-none">Notas</a>
        {% endif %}

        {% if permissions.destroy %}
        <button type="button" onclick="deleteServiceRequest(this)"
                data-element="{{ parse_service_request(element) }}"
                class="btn btn-outline-danger">Eliminar</button>
        {% endif %}
</div>

admin/src/web/templates/modules/service_requests/service_requests_list.html
<div class="container">
    <h3 class="text-start pb-4 pt-2"> {{ title }} </h3>
    <div class="mx-1 row justify-content-between align-items-center flex-column flex-sm-row ">

        {% if 'service_requests.service_requests' in request.endpoint %}
            {% include "modules/service_requests/filters.html" %}
        {% endif %}

    </div>
    <div class="list-group ">
        {% if not elements.items %}
        <h5 class="text-center pb-4 pt-4"> No hay elementos para mostrar </h5>
        {% endif %}
        {% for element in elements.items %}
        {% if loop.first or element.service.name != elements.items[loop.index0 - 1].service.name %}
        <div class="d-flex py-4" >
            <h3><span class="badge badge-info">{{ element.service.name }}</span></h3>
        </div>
        {% endif %}
        <div class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between flex-column flex-sm-row">
                <h6 class="pt-2"> {{ element.title }} </h6>
                {% include "modules/service_requests/service_requests_actions.html" %}
            </div>

        </div>
        {% endfor %}
    </div>
</div>
<div style="width:100%; height: 50px">

</div>